name: Windows

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test Windows
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "7.0.x"

      - name: Build and test Windows projects
        shell: pwsh
        run: ./scripts/build-windows.ps1
